#databases:
#  - name: gaia
#    databaseName: db.sqlite3
#    user: star

services:
  - type: web
    name: gaia
    env: python 3.10.1
    buildCommand: "./build.sh"
    startCommand: "gunicorn gaia.wsgi:application"
#    envVars:
#      - key: DATABASE_URL
#        fromDatabase:
#          name: mysite
#          property: connectionString
#      - key: SECRET_KEY
#        generateValue: true
#      - key: WEB_CONCURRENCY
#        value: 4