# Generated by Django 4.1.3 on 2022-12-08 19:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(null=True, upload_to='product/img', verbose_name='Imagen Principal')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='datos_generales/logo', verbose_name='Logo')),
                ('img_principal', models.ImageField(upload_to='datos_generales/img_principal', verbose_name='Imagen Principal')),
                ('enterprise_name', models.CharField(max_length=100, verbose_name='Nombre de la empresa')),
                ('enterprise_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección de la empresa')),
                ('email', models.EmailField(error_messages={'unique': 'Este correo ya existe'}, max_length=254, unique=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Datos Generales',
                'verbose_name_plural': 'Datos Generales',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product/img', verbose_name='Imagen Principal')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Este precio debería ser mayor al precio actual', max_digits=9, null=True, verbose_name='Precio anterior')),
                ('info', ckeditor.fields.RichTextField(max_length=400, verbose_name='Información')),
                ('about', ckeditor.fields.RichTextField(max_length=400, verbose_name='Sobre el producto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visible')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.category', verbose_name='Categoría')),
            ],
        ),
    ]
