# Generated by Django 4.1.5 on 2023-03-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='meta_description',
            field=models.TextField(default='GAIA', help_text='Search Engine Optimization (SEO)', verbose_name='Meta etiqueta descripción'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='meta_kw',
            field=models.TextField(default='GAIA', help_text='Search Engine Optimization (SEO)', verbose_name='Meta etiqueta palabras clave'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='meta_tittle',
            field=models.CharField(default='GAIA', help_text='Search Engine Optimization (SEO)', max_length=255, verbose_name='Meta etiqueta título'),
        ),
    ]
