# Generated by Django 4.1.3 on 2022-12-09 03:18

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Facebook'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Instagram'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='phone_number',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya este teléfono está registrado'}, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe estar en este formato: +9999999999. Hasta 15 dígitos permitidos.', regex='\\+?1?\\d{9,15}$')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='product',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True, verbose_name='Sobre el producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=ckeditor.fields.RichTextField(blank=True, max_length=400, null=True, verbose_name='Información'),
        ),
    ]
