# Generated by Django 4.1.3 on 2023-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='tiempo_de_entrega',
            field=models.PositiveIntegerField(default=3, verbose_name='Tiempo de entrega máximo'),
            preserve_default=False,
        ),
    ]
