# Generated by Django 4.1.3 on 2023-01-26 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_orden_tiempo_de_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenteorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componente_producto', to='app_main.product'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('1', 'Completada'), ('2', 'Pendiente'), ('3', 'Cancelada por cliente')], default='2', max_length=10, verbose_name='Estado'),
        ),
    ]
