# Generated by Django 4.1.5 on 2023-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_generaldata_meta_description_generaldata_meta_kw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
