# Generated by Django 4.1.3 on 2022-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_generaldata_facebook_generaldata_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_important',
            field=models.BooleanField(default=True, verbose_name='Destacado'),
        ),
    ]
