# Generated by Django 4.1.3 on 2023-01-27 05:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_componenteorden_producto_alter_orden_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componenteorden',
            options={'ordering': ('orden', 'producto'), 'verbose_name': 'Componente de orden', 'verbose_name_plural': 'Componentes de ordenes'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ('moneda', '-status', 'date_created'), 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.AlterField(
            model_name='infoutil',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
