# Generated by Django 4.1.5 on 2023-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_remove_category_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'verbose_name': 'Reparto', 'verbose_name_plural': 'Repartos'},
        ),
        migrations.RemoveField(
            model_name='orden',
            name='reparto',
        ),
        migrations.AlterField(
            model_name='orden',
            name='municipio',
            field=models.CharField(max_length=200, verbose_name='Reparto'),
        ),
    ]
