# Generated by Django 4.1.5 on 2023-06-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_municipio_options_remove_orden_reparto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
