# Generated by Django 4.1.3 on 2022-12-21 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_alter_product_options_generaldata_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaldata',
            name='banner',
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='datos_generales/banner', verbose_name='Banner')),
                ('gnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.generaldata')),
            ],
        ),
    ]
