# Generated by Django 4.1.5 on 2023-08-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_municipio_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='checkout_allowed',
            field=models.BooleanField(default=True, help_text='Permitir a los usuarios realizar compras', verbose_name='Permitir compras'),
        ),
        migrations.AddField(
            model_name='generaldata',
            name='closed_message',
            field=models.CharField(default='Lo sentimos, estamos cerrados.', help_text='Texto a mostrar cuando la tienda está cerrada', max_length=255, verbose_name='Mensaje de Cerrado'),
        ),
    ]
