# Generated by Django 4.1.3 on 2023-01-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_remove_infoutil_text_contenidoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='correo',
            field=models.EmailField(default='mario@gaia.com', max_length=254, verbose_name='Correo del comprador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre_comprador',
            field=models.CharField(max_length=200, verbose_name='Nombre del comprador'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre_receptor',
            field=models.CharField(max_length=200, verbose_name='Nombre del receptor'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='telefono_comprador',
            field=models.CharField(max_length=200, verbose_name='Teléfono del comprador'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='telefono_receptor',
            field=models.CharField(max_length=200, verbose_name='Teléfono del receptor'),
        ),
    ]
