# Generated by Django 4.1.5 on 2023-09-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_generaldata_checkout_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/img', verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='correo',
            field=models.EmailField(blank=True, help_text='No necesario para compras en C.U.P', max_length=254, null=True, verbose_name='Correo del comprador'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='nombre_receptor',
            field=models.CharField(blank=True, help_text='Eliminado', max_length=200, null=True, verbose_name='Nombre del receptor'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='telefono_receptor',
            field=models.CharField(blank=True, help_text='Eliminado', max_length=200, null=True, verbose_name='Teléfono del receptor'),
        ),
    ]
