# Generated by Django 4.1.5 on 2023-01-28 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_orden_correo_alter_orden_nombre_comprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='tropipay_impuesto',
            field=models.FloatField(default=3.45, help_text='Valor que se multiplica al total de la orden', validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Impuesto de Tropipay'),
        ),
    ]
