# Generated by Django 4.1.3 on 2022-12-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Tiempo de entrega (días)'),
            preserve_default=False,
        ),
    ]
