# Generated by Django 4.1.5 on 2023-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_alter_category_image_alter_orden_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='is_pickup_place',
            field=models.BooleanField(default=False, verbose_name='Punto de recogida'),
        ),
    ]
