# Generated by Django 4.1.5 on 2023-02-04 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_generaldata_tropipay_impuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='tropipay_impuesto',
            field=models.FloatField(default=3.45, help_text='Porciento del total de la orden aumentado', validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Impuesto de Tropipay'),
        ),
    ]
