# Generated by Django 4.1.5 on 2023-09-08 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0008_municipio_is_pickup_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('card', models.CharField(max_length=255, verbose_name='Número de Tarjeta')),
                ('confirmation_number', models.CharField(max_length=255, verbose_name='Móvil a Confirmar')),
                ('type', models.CharField(choices=[('cup', 'C.U.P'), ('mlc', 'MLC')], default='cup', max_length=255, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Método Extra de Pago',
                'verbose_name_plural': 'Métodos Extra de Pago',
            },
        ),
        migrations.AddField(
            model_name='generaldata',
            name='tasa_mlc',
            field=models.FloatField(default=200, help_text='Valor del MLC en CUP', validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Tasa de cambio MLC'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='taza_cambio',
            field=models.FloatField(help_text='Valor del Euro en CUP', validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Tasa de cambio'),
        ),
        migrations.CreateModel(
            name='ProductExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/img', verbose_name='Imagen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.product')),
            ],
            options={
                'verbose_name': 'Imagen Extra',
                'verbose_name_plural': 'Imágenes Extra',
            },
        ),
    ]
