# Generated by Django 4.1.5 on 2023-02-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_alter_orden_detalles_direccion_alter_orden_reparto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('1', 'Completada'), ('2', 'Pendiente'), ('3', 'Cancelada')], default='2', max_length=10, verbose_name='Estado'),
        ),
    ]
