# Generated by Django 4.1.5 on 2023-09-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_extrapaymentmethod_generaldata_tasa_mlc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código del Sistema'),
        ),
    ]
