# Generated by Django 4.1.3 on 2023-01-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0010_alter_product_options_alter_suscriptor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoutil',
            options={'verbose_name': 'Información útil', 'verbose_name_plural': 'Informaciones útiles'},
        ),
        migrations.RemoveField(
            model_name='infoutil',
            name='gnd',
        ),
    ]
