# Generated by Django 4.1.3 on 2023-01-15 08:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_alter_infoutil_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField(default=8, verbose_name='Precio de envío')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('total', models.FloatField(default=0, verbose_name='Importe total')),
                ('precio_envio', models.FloatField(default=0, verbose_name='Precio de envío')),
                ('destinatario', models.TextField()),
                ('moneda', models.CharField(default='EUR', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.CreateModel(
            name='ComponenteOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respaldo', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componente_producto', to='app_main.product')),
            ],
        ),
    ]
