# Generated by Django 4.1.5 on 2023-09-28 03:50

import app_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_alter_category_color_alter_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calification', models.PositiveIntegerField(validators=[app_main.models.validate_calification], verbose_name='Calificacion')),
                ('comment', models.TextField(null=True, verbose_name='Commentario')),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opinions',
            },
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ('-date_created', '-status'), 'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
    ]
