# Generated by Django 4.1.3 on 2023-01-17 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_municipio_orden_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='taza_cambio',
            field=models.FloatField(default=1.6, validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Taza de cambio'),
            preserve_default=False,
        ),
    ]
