# Generated by Django 4.1.3 on 2023-01-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='moneda',
            field=models.CharField(blank=True, choices=[], max_length=200, null=True, verbose_name='Moneda principal'),
        ),
    ]
