# Generated by Django 4.1.3 on 2023-01-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_product_moneda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moneda',
        ),
        migrations.AlterField(
            model_name='product',
            name='moneda',
            field=models.CharField(choices=[('CUP', 'CUP'), ('Euro', 'Euro')], default='CUP', max_length=200, verbose_name='Moneda principal'),
        ),
    ]
