# Generated by Django 4.1.3 on 2023-01-23 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0017_delete_moneda_alter_product_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='receptor',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[('1', 'Completada'), ('2', 'Pendiente')], default='2', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='generaldata',
            name='taza_cambio',
            field=models.FloatField(help_text='Valor del Euro en CUP', validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor que cero')], verbose_name='Taza de cambio'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='precio',
            field=models.FloatField(help_text='Si el pago es en Euro, se hará la conversión en base a la taza de cambio', verbose_name='Precio de envío en CUP'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='moneda',
            field=models.CharField(default='Euro', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='moneda',
            field=models.CharField(choices=[('CUP', 'CUP'), ('Euro', 'Euro'), ('Ambas', 'Ambas')], default='CUP', max_length=200, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Poner en base a CUP', max_digits=9, verbose_name='Precio'),
        ),
    ]
