# Generated by Django 4.1.3 on 2023-01-23 19:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0018_orden_receptor_orden_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
