# Generated by Django 4.1.3 on 2023-01-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0020_orden_link_de_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacada'),
        ),
    ]
