# Generated by Django 4.1.3 on 2023-01-24 23:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0021_remove_category_description_category_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='precio_euro',
            field=models.FloatField(default=5.2, verbose_name='Precio de envío en Euro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infoutil',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='infoutil',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='precio',
            field=models.FloatField(verbose_name='Precio de envío en CUP'),
        ),
    ]
