# Generated by Django 4.1.3 on 2023-01-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0022_municipio_precio_euro_alter_infoutil_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='receptor',
        ),
        migrations.AddField(
            model_name='componenteorden',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='componente_orden', to='app_main.orden'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='calle',
            field=models.CharField(default='asd', max_length=200, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='calle1',
            field=models.CharField(default='asd', max_length=200, verbose_name='Entre calle 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='calle2',
            field=models.CharField(default='asd', max_length=200, verbose_name='Entre calle 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='detalles_direccion',
            field=models.CharField(default='asd', max_length=200, verbose_name='Detalles de dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='municipio',
            field=models.CharField(default='asd', max_length=200, verbose_name='Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre_comprador',
            field=models.CharField(default='asd', max_length=200, verbose_name='Nombre comprador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='nombre_receptor',
            field=models.CharField(default='asd', max_length=200, verbose_name='Nombre receptor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='numero_edificio',
            field=models.CharField(default='asd', max_length=200, verbose_name='Número de edificio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='reparto',
            field=models.CharField(default='asd', max_length=200, verbose_name='Reparto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono_comprador',
            field=models.CharField(default='asd', max_length=200, verbose_name='Teléfono comprador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='telefono_receptor',
            field=models.CharField(default='asd', max_length=200, verbose_name='Teléfono receptor'),
            preserve_default=False,
        ),
    ]
